### PR TITLE
Analisis servicios

### PR DESCRIPTION
**Pull request by furilo**

### CODE REVIEW

**Comment by ferblape** [comment]
@furilo which Ruby version are you using, I can't start the project because of a misterious error:

```$ bundle exec jekyll s --future --incremental --livereload --trace
Configuration file: /Users/fernando/proyectos/gobierto.es/_config.yml
            Source: /Users/fernando/proyectos/gobierto.es
       Destination: /Users/fernando/proyectos/gobierto.es/_site
 Incremental build: enabled
      Generating...
bundler: failed to load command: jekyll (/usr/local/var/rbenv/versions/2.6.5/bin/jekyll)
ArgumentError: wrong number of arguments (given 2, expected 1)
```

**Comment by furilo** [comment]
2.6.5

I've changed some things, I don't think it was on this branch, but try
doing a bundle install?

**Comment by ferblape** [comment]
Ok, it was an issue with sprockets version. I've pushed the fix, please confirm it works for you too (after `git pull` run `bundle install`).

But in the PR I can't see the new content. Are you creating services as a post? I see you added assets but not any page or post.

**Comment by furilo** [comment]
🤦‍♂️here you go

**Comment by furilo** [comment]
Done !

**Pull request merged**
